# Only needed if you want to download files from CC
my_login: "dcarabad"
my_domain: "cca.in2p3.fr"

# Tag used for the plots
tag: "OARun11A preliminary"

dir_ver: "OA2023"

# For Bievent plot
oaver:  "OA2023"
include_320kA: False
data_kind: "data"

sample_titles: ['numu1R', 'nue1R', 'numubar1R', 'nuebar1R', 'numucc1pi', 'nue1RD']